"""002 workflow tables: collections, collection_papers, triage_states, triage_log, saved_queries

Revision ID: 002
Revises: 001
Create Date: 2026-03-09

Hand-written migration (not autogenerated) per Phase 1 convention.
Creates 5 workflow tables for Phase 2: collections, triage, and saved queries.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "002"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- 1. collections table ---
    op.create_table(
        "collections",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("slug", sa.String(128), unique=True, nullable=False),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default="false"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    # --- 2. collection_papers table ---
    op.create_table(
        "collection_papers",
        sa.Column(
            "collection_id",
            sa.Integer(),
            sa.ForeignKey("collections.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "paper_id",
            sa.String(20),
            sa.ForeignKey("papers.arxiv_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("source", sa.String(32), server_default="manual"),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("collection_id", "paper_id"),
    )
    op.create_index(
        "idx_collection_papers_paper_id",
        "collection_papers",
        ["paper_id"],
    )

    # --- 3. triage_states table ---
    op.create_table(
        "triage_states",
        sa.Column(
            "paper_id",
            sa.String(20),
            sa.ForeignKey("papers.arxiv_id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("state", sa.String(20), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('shortlisted', 'dismissed', 'read', 'cite-later', 'archived')",
            name="ck_triage_state_valid",
        ),
    )
    op.create_index(
        "idx_triage_states_state",
        "triage_states",
        ["state"],
    )

    # --- 4. triage_log table ---
    op.create_table(
        "triage_log",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "paper_id",
            sa.String(20),
            sa.ForeignKey("papers.arxiv_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("old_state", sa.String(20), nullable=False),
        sa.Column("new_state", sa.String(20), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(32), server_default="manual"),
        sa.Column("reason", sa.Text()),
    )
    op.create_index(
        "idx_triage_log_paper_timestamp",
        "triage_log",
        ["paper_id", "timestamp"],
    )

    # --- 5. saved_queries table ---
    op.create_table(
        "saved_queries",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("slug", sa.String(128), unique=True, nullable=False),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("params", postgresql.JSONB(), nullable=False),
        sa.Column("run_count", sa.Integer(), server_default="0"),
        sa.Column("last_run_at", sa.DateTime(timezone=True)),
        sa.Column("is_watch", sa.Boolean(), server_default="false"),
        sa.Column("cadence_hint", sa.String(20)),
        sa.Column("checkpoint_date", sa.Date()),
        sa.Column("last_checked_at", sa.DateTime(timezone=True)),
        sa.Column("is_paused", sa.Boolean(), server_default="false"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )


def downgrade() -> None:
    # Drop in reverse order to respect FK dependencies
    op.drop_table("saved_queries")

    op.drop_index("idx_triage_log_paper_timestamp", table_name="triage_log")
    op.drop_table("triage_log")

    op.drop_index("idx_triage_states_state", table_name="triage_states")
    op.drop_table("triage_states")

    op.drop_index("idx_collection_papers_paper_id", table_name="collection_papers")
    op.drop_table("collection_papers")

    op.drop_table("collections")
