"""006 enrichment composite PK: (arxiv_id, source_api)

Revision ID: 006
Revises: 005
Create Date: 2026-03-11

Hand-written migration (not autogenerated) per Phase 1 convention.
Changes paper_enrichments primary key from arxiv_id alone to
(arxiv_id, source_api), enabling multiple enrichment sources per paper.

Note: downgrade may fail if multiple source_api records exist per arxiv_id,
since the single-column PK cannot accommodate duplicate arxiv_id values.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "006"
down_revision = "005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Drop existing indexes (they reference the table which we're altering)
    op.drop_index("idx_enrichments_status", table_name="paper_enrichments")
    op.drop_index("idx_enrichments_enriched_at", table_name="paper_enrichments")

    # 2. Drop old single-column PK
    op.drop_constraint("paper_enrichments_pkey", "paper_enrichments", type_="primary")

    # 3. Create new composite PK
    op.create_primary_key(
        "paper_enrichments_pkey",
        "paper_enrichments",
        ["arxiv_id", "source_api"],
    )

    # 4. Re-create indexes
    op.create_index("idx_enrichments_status", "paper_enrichments", ["status"])
    op.create_index("idx_enrichments_enriched_at", "paper_enrichments", ["enriched_at"])


def downgrade() -> None:
    # Note: downgrade will fail if multiple source_api records exist per arxiv_id
    op.drop_index("idx_enrichments_status", table_name="paper_enrichments")
    op.drop_index("idx_enrichments_enriched_at", table_name="paper_enrichments")

    op.drop_constraint("paper_enrichments_pkey", "paper_enrichments", type_="primary")

    op.create_primary_key(
        "paper_enrichments_pkey",
        "paper_enrichments",
        ["arxiv_id"],
    )

    op.create_index("idx_enrichments_status", "paper_enrichments", ["status"])
    op.create_index("idx_enrichments_enriched_at", "paper_enrichments", ["enriched_at"])
