"""007 add 'seen' to triage state CHECK constraint

Revision ID: 007
Revises: 006
Create Date: 2026-03-12

Hand-written migration (not autogenerated) per Phase 1 convention.
Adds 'seen' to the TriageState CHECK constraint. 'Seen' represents
"encountered, decision pending" -- distinct from absence (unseen/never
encountered) and from decisions (shortlisted/dismissed/etc).

PREMCP-02: Restores the 'seen' state that was intended in WKFL-03
but dropped during Phase 2 implementation.
"""

from alembic import op


# revision identifiers, used by Alembic
revision = "007"
down_revision = "006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop old CHECK constraint
    op.drop_constraint("ck_triage_state_valid", "triage_states", type_="check")
    # Create new CHECK constraint including 'seen'
    op.create_check_constraint(
        "ck_triage_state_valid",
        "triage_states",
        "state IN ('seen', 'shortlisted', 'dismissed', 'read', 'cite-later', 'archived')",
    )


def downgrade() -> None:
    # Drop new CHECK constraint
    op.drop_constraint("ck_triage_state_valid", "triage_states", type_="check")
    # Recreate old CHECK constraint without 'seen'
    op.create_check_constraint(
        "ck_triage_state_valid",
        "triage_states",
        "state IN ('shortlisted', 'dismissed', 'read', 'cite-later', 'archived')",
    )
