"""008 create content_variants table

Revision ID: 008
Revises: 007
Create Date: 2026-03-12

Hand-written migration (not autogenerated) per Phase 1 convention.
Creates the content_variants table for storing normalized paper content
in multiple formats with full provenance tracking.

CONT-01: Content variant data model
CONT-02: Provenance tracking for content sources
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic
revision = "008"
down_revision = "007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "content_variants",
        sa.Column("arxiv_id", sa.String(20), nullable=False),
        sa.Column("variant_type", sa.String(32), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("content_hash", sa.String(64), nullable=True),
        sa.Column("source_url", sa.String(512), nullable=True),
        sa.Column("backend", sa.String(32), nullable=True),
        sa.Column("backend_version", sa.String(32), nullable=True),
        sa.Column("extraction_method", sa.String(32), nullable=True),
        sa.Column("license_uri", sa.String(256), nullable=True),
        sa.Column("quality_warnings", JSONB, nullable=True),
        sa.Column(
            "fetched_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "converted_at", sa.DateTime(timezone=True), nullable=False
        ),
        # Composite primary key
        sa.PrimaryKeyConstraint("arxiv_id", "variant_type", name="content_variants_pkey"),
        # Foreign key to papers
        sa.ForeignKeyConstraint(
            ["arxiv_id"],
            ["papers.arxiv_id"],
            name="fk_content_variants_paper",
            ondelete="CASCADE",
        ),
        # CHECK constraint on variant_type
        sa.CheckConstraint(
            "variant_type IN ('abstract', 'html', 'source_derived', 'pdf_markdown')",
            name="ck_content_variant_type_valid",
        ),
    )
    # Index on arxiv_id for FK lookups
    op.create_index(
        "idx_content_variants_arxiv_id",
        "content_variants",
        ["arxiv_id"],
    )


def downgrade() -> None:
    op.drop_index("idx_content_variants_arxiv_id", table_name="content_variants")
    op.drop_table("content_variants")
