"""001 initial schema: papers table with tsvector trigger

Revision ID: 001
Revises:
Create Date: 2026-03-09

Hand-written migration (not autogenerated) per research pitfall 5:
Alembic autogenerate has issues with tsvector GIN index comparison,
producing spurious migration files. The tsvector trigger and GIN index
are created explicitly here.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- Create papers table ---
    op.create_table(
        "papers",
        # Identity
        sa.Column("arxiv_id", sa.String(20), primary_key=True),
        # Core metadata
        sa.Column("title", sa.Text()),
        sa.Column("authors_text", sa.Text()),
        sa.Column("abstract", sa.Text()),
        sa.Column("submitter", sa.String(256)),
        sa.Column("comments", sa.Text()),
        sa.Column("journal_ref", sa.Text()),
        sa.Column("report_no", sa.String(256)),
        # Classification
        sa.Column("categories", sa.Text(), nullable=False),
        sa.Column("primary_category", sa.String(20)),
        sa.Column("category_list", postgresql.ARRAY(sa.String())),
        sa.Column("msc_class", sa.String(256)),
        sa.Column("acm_class", sa.String(256)),
        # External identifiers
        sa.Column("doi", sa.String(256)),
        sa.Column("openalex_id", sa.String(32)),
        sa.Column("semantic_scholar_id", sa.String(64)),
        # Time semantics (INGS-03)
        sa.Column("submitted_date", sa.DateTime(timezone=True)),
        sa.Column("updated_date", sa.DateTime(timezone=True)),
        sa.Column("announced_date", sa.Date()),
        sa.Column("oai_datestamp", sa.Date()),
        # Rights (INGS-04)
        sa.Column("license_uri", sa.String(256)),
        # Version info
        sa.Column("latest_version", sa.Integer()),
        sa.Column("version_history", postgresql.JSONB()),
        # Processing tier
        sa.Column("processing_tier", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("promotion_reason", sa.String(64)),
        # Provenance (PAPR-04)
        sa.Column("source", sa.String(32), nullable=False, server_default="oai_pmh"),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_metadata_update", sa.DateTime(timezone=True)),
        # Full-text search vector
        sa.Column("search_vector", postgresql.TSVECTOR()),
    )

    # --- Create indexes ---
    # GIN index on tsvector for full-text search
    op.create_index(
        "idx_papers_search_vector",
        "papers",
        ["search_vector"],
        postgresql_using="gin",
    )

    # GIN index on category_list array for array containment queries
    op.create_index(
        "idx_papers_categories_gin",
        "papers",
        ["category_list"],
        postgresql_using="gin",
    )

    # B-tree indexes on date columns for range queries and ordering
    op.create_index("idx_papers_primary_category", "papers", ["primary_category"])
    op.create_index("idx_papers_submitted_date", "papers", ["submitted_date"])
    op.create_index("idx_papers_announced_date", "papers", ["announced_date"])
    op.create_index("idx_papers_updated_date", "papers", ["updated_date"])
    op.create_index("idx_papers_oai_datestamp", "papers", ["oai_datestamp"])
    op.create_index("idx_papers_processing_tier", "papers", ["processing_tier"])

    # --- Create tsvector trigger function ---
    # Weighted search: title=A (highest), authors=B, abstract=C
    # Title and abstract use 'english' config for stemming.
    # Authors use 'simple' config (no stemming for proper names).
    op.execute("""
        CREATE FUNCTION papers_search_vector_update() RETURNS trigger AS $$
        BEGIN
          NEW.search_vector :=
            setweight(to_tsvector('english', COALESCE(NEW.title, '')), 'A') ||
            setweight(to_tsvector('simple', COALESCE(NEW.authors_text, '')), 'B') ||
            setweight(to_tsvector('english', COALESCE(NEW.abstract, '')), 'C');
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # --- Create trigger ---
    op.execute("""
        CREATE TRIGGER papers_search_vector_trigger
          BEFORE INSERT OR UPDATE ON papers
          FOR EACH ROW EXECUTE FUNCTION papers_search_vector_update();
    """)


def downgrade() -> None:
    # Drop trigger first, then function, then indexes, then table
    op.execute("DROP TRIGGER IF EXISTS papers_search_vector_trigger ON papers;")
    op.execute("DROP FUNCTION IF EXISTS papers_search_vector_update();")

    op.drop_index("idx_papers_processing_tier", table_name="papers")
    op.drop_index("idx_papers_oai_datestamp", table_name="papers")
    op.drop_index("idx_papers_updated_date", table_name="papers")
    op.drop_index("idx_papers_announced_date", table_name="papers")
    op.drop_index("idx_papers_submitted_date", table_name="papers")
    op.drop_index("idx_papers_primary_category", table_name="papers")
    op.drop_index("idx_papers_categories_gin", table_name="papers")
    op.drop_index("idx_papers_search_vector", table_name="papers")

    op.drop_table("papers")
