"""003 interest tables: interest_profiles, interest_signals

Revision ID: 003
Revises: 002
Create Date: 2026-03-10

Hand-written migration (not autogenerated) per Phase 1 convention.
Creates 2 interest tables for Phase 3: profiles and signals.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "003"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- 1. interest_profiles table ---
    op.create_table(
        "interest_profiles",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("slug", sa.String(128), unique=True, nullable=False),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default="false"),
        sa.Column("negative_weight", sa.Float(), server_default="0.3"),
        sa.Column("weights", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    # --- 2. interest_signals table ---
    op.create_table(
        "interest_signals",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "profile_id",
            sa.Integer(),
            sa.ForeignKey("interest_profiles.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("signal_type", sa.String(32), nullable=False),
        sa.Column("signal_value", sa.String(256), nullable=False),
        sa.Column("status", sa.String(20), server_default="active"),
        sa.Column("source", sa.String(32), server_default="manual"),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "signal_type IN ('seed_paper', 'saved_query', 'followed_author', 'negative_example')",
            name="ck_signal_type_valid",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'pending', 'dismissed')",
            name="ck_signal_status_valid",
        ),
        sa.UniqueConstraint(
            "profile_id", "signal_type", "signal_value",
            name="uq_interest_signals_profile_type_value",
        ),
    )
    op.create_index(
        "idx_interest_signals_profile_type",
        "interest_signals",
        ["profile_id", "signal_type"],
    )


def downgrade() -> None:
    # Drop in reverse order to respect FK dependencies
    op.drop_index("idx_interest_signals_profile_type", table_name="interest_signals")
    op.drop_table("interest_signals")
    op.drop_table("interest_profiles")
