"""004 enrichment table: paper_enrichments

Revision ID: 004
Revises: 003
Create Date: 2026-03-10

Hand-written migration (not autogenerated) per Phase 1 convention.
Creates paper_enrichments table for Phase 4 enrichment data storage.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "004"
down_revision = "003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "paper_enrichments",
        sa.Column(
            "arxiv_id",
            sa.String(20),
            sa.ForeignKey("papers.arxiv_id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("openalex_id", sa.String(64), nullable=True),
        sa.Column("doi", sa.String(256), nullable=True),
        sa.Column("cited_by_count", sa.Integer(), nullable=True),
        sa.Column("fwci", sa.Float(), nullable=True),
        sa.Column("topics", postgresql.JSONB(), nullable=True),
        sa.Column("related_works", postgresql.JSONB(), nullable=True),
        sa.Column("counts_by_year", postgresql.JSONB(), nullable=True),
        sa.Column("openalex_type", sa.String(64), nullable=True),
        sa.Column("openalex_raw", postgresql.JSONB(), nullable=True),
        sa.Column(
            "source_api", sa.String(32), nullable=False, server_default="openalex"
        ),
        sa.Column("api_version", sa.String(32), nullable=True),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('success', 'not_found', 'partial', 'error')",
            name="ck_enrichment_status_valid",
        ),
    )
    op.create_index(
        "idx_enrichments_status", "paper_enrichments", ["status"]
    )
    op.create_index(
        "idx_enrichments_enriched_at", "paper_enrichments", ["enriched_at"]
    )


def downgrade() -> None:
    op.drop_index("idx_enrichments_enriched_at", table_name="paper_enrichments")
    op.drop_index("idx_enrichments_status", table_name="paper_enrichments")
    op.drop_table("paper_enrichments")
