"""005 drop signal_type CHECK constraint

Revision ID: 005
Revises: 004
Create Date: 2026-03-11

Hand-written migration (not autogenerated) per Phase 1 convention.
Drops ck_signal_type_valid CHECK constraint from interest_signals.
Signal type validation moves to application level (signals.py VALID_SIGNAL_TYPES),
allowing new signal types without DB migrations.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "005"
down_revision = "004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_constraint("ck_signal_type_valid", "interest_signals", type_="check")


def downgrade() -> None:
    op.create_check_constraint(
        "ck_signal_type_valid",
        "interest_signals",
        "signal_type IN ('seed_paper', 'saved_query', 'followed_author', 'negative_example')",
    )
