"""Suggestion engine for interest profiles.

Generates suggestions from workflow activity (triaged papers, frequent
queries, recurring authors), allows adding them as pending signals,
and supports confirm/dismiss lifecycle.

Suggestion candidates are generated by examining:
1. Papers triaged as shortlisted or cite-later -> seed_paper suggestions
2. Saved queries run 3+ times -> saved_query suggestions
3. Authors appearing in 3+ shortlisted/cite-later papers -> followed_author suggestions

All candidates include a human-readable reason explaining why they were
suggested, and are sorted by score descending.
"""

from __future__ import annotations

import logging
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from arxiv_mcp.config import Settings
from arxiv_mcp.db.models import (
    InterestProfile,
    InterestSignal,
    Paper,
    SavedQuery,
    TriageState,
)
from arxiv_mcp.interest.profiles import ProfileService
from arxiv_mcp.interest.signals import parse_authors
from arxiv_mcp.models.interest import SignalInfo

logger = logging.getLogger(__name__)

# Minimum number of shortlisted/cite-later papers by an author
# before suggesting them as a followed_author signal.
AUTHOR_THRESHOLD = 3

# Minimum run_count for a saved query to be suggested.
QUERY_RUN_THRESHOLD = 3


@dataclass
class SuggestionCandidate:
    """A candidate suggestion for an interest profile.

    Attributes:
        signal_type: Type of signal (seed_paper, saved_query, followed_author).
        signal_value: The value (arxiv_id, query slug, or author name).
        reason: Human-readable explanation of why this was suggested.
        score: How strongly suggested (e.g., frequency count, run count).
    """

    signal_type: str
    signal_value: str
    reason: str
    score: float


class SuggestionService:
    """Generates, manages, and resolves interest profile suggestions.

    Examines workflow activity (triaged papers, saved queries) to find
    candidate signals. Supports adding candidates as pending signals,
    confirming them to active, or dismissing them.

    Args:
        session_factory: Async session factory for DB queries.
        settings: Application settings.
        profile_service: ProfileService for profile/signal operations.
    """

    def __init__(
        self,
        session_factory: async_sessionmaker[AsyncSession],
        settings: Settings,
        profile_service: ProfileService,
    ) -> None:
        self.session_factory = session_factory
        self.settings = settings
        self.profile_service = profile_service

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def generate_suggestions(
        self, profile_slug: str
    ) -> list[SuggestionCandidate]:
        """Generate suggestion candidates from workflow activity.

        Loads the profile to identify existing signals (active + dismissed)
        to exclude. Calls internal suggestion generators for seed papers,
        queries, and authors. Returns combined candidates sorted by score
        descending.

        Args:
            profile_slug: Slug of the profile to generate suggestions for.

        Returns:
            List of SuggestionCandidate, sorted by score descending.
        """
        async with self.session_factory() as session:
            # Load profile with signals to determine exclusions
            profile = await self._get_profile(session, profile_slug)
            if profile is None:
                raise ValueError(f"Profile {profile_slug!r} not found")

            # Build exclusion sets: active + pending + dismissed signals
            existing_by_type: dict[str, set[str]] = {}
            for signal in profile.signals:
                st = signal.signal_type
                if st not in existing_by_type:
                    existing_by_type[st] = set()
                existing_by_type[st].add(signal.signal_value)

            candidates: list[SuggestionCandidate] = []

            # Generate each type
            seeds = await self._suggest_seed_papers(session, existing_by_type)
            candidates.extend(seeds)

            queries = await self._suggest_queries(session, existing_by_type)
            candidates.extend(queries)

            authors = await self._suggest_authors(session, existing_by_type)
            candidates.extend(authors)

            # Sort by score descending
            candidates.sort(key=lambda c: c.score, reverse=True)
            return candidates

    async def add_suggestions_to_profile(
        self,
        profile_slug: str,
        candidates: list[SuggestionCandidate],
    ) -> list[SignalInfo]:
        """Add suggestion candidates as pending signals in a profile.

        For each candidate, calls profile_service.add_signal with
        source="suggestion" which sets status="pending".

        Args:
            profile_slug: Profile to add suggestions to.
            candidates: List of candidates to add.

        Returns:
            List of created SignalInfo objects.
        """
        results: list[SignalInfo] = []
        for candidate in candidates:
            try:
                info = await self.profile_service.add_signal(
                    slug=profile_slug,
                    signal_type=candidate.signal_type,
                    signal_value=candidate.signal_value,
                    source="suggestion",
                    reason=candidate.reason,
                )
                results.append(info)
            except ValueError as e:
                # Signal already exists (duplicate) -- skip silently
                logger.debug(
                    "Skipping duplicate suggestion: %s", e
                )
        return results

    async def confirm_suggestion(
        self,
        profile_slug: str,
        signal_type: str,
        signal_value: str,
    ) -> SignalInfo:
        """Confirm a pending suggestion, changing status to active.

        Args:
            profile_slug: Profile slug.
            signal_type: Signal type of the suggestion.
            signal_value: Signal value of the suggestion.

        Returns:
            Updated SignalInfo with status="active".

        Raises:
            ValueError: If no pending signal matches.
        """
        async with self.session_factory() as session:
            profile = await self._get_profile(session, profile_slug)
            if profile is None:
                raise ValueError(f"Profile {profile_slug!r} not found")

            signal = await self._find_pending_signal(
                session, profile.id, signal_type, signal_value
            )
            signal.status = "active"
            await session.commit()
            return SignalInfo.model_validate(signal, from_attributes=True)

    async def dismiss_suggestion(
        self,
        profile_slug: str,
        signal_type: str,
        signal_value: str,
    ) -> None:
        """Dismiss a pending suggestion, changing status to dismissed.

        Dismissed signals are excluded from future suggestion generation.

        Args:
            profile_slug: Profile slug.
            signal_type: Signal type of the suggestion.
            signal_value: Signal value of the suggestion.

        Raises:
            ValueError: If no pending signal matches.
        """
        async with self.session_factory() as session:
            profile = await self._get_profile(session, profile_slug)
            if profile is None:
                raise ValueError(f"Profile {profile_slug!r} not found")

            signal = await self._find_pending_signal(
                session, profile.id, signal_type, signal_value
            )
            signal.status = "dismissed"
            await session.commit()

    async def confirm_suggestions_bulk(
        self,
        profile_slug: str,
        items: list[tuple[str, str]],
    ) -> int:
        """Confirm multiple pending suggestions at once.

        Args:
            profile_slug: Profile slug.
            items: List of (signal_type, signal_value) tuples to confirm.

        Returns:
            Number of suggestions confirmed.
        """
        count = 0
        for signal_type, signal_value in items:
            try:
                await self.confirm_suggestion(profile_slug, signal_type, signal_value)
                count += 1
            except ValueError:
                logger.warning(
                    "Could not confirm (%s, %s) in %s",
                    signal_type, signal_value, profile_slug,
                )
        return count

    # ------------------------------------------------------------------
    # Internal suggestion generators
    # ------------------------------------------------------------------

    async def _suggest_seed_papers(
        self,
        session: AsyncSession,
        existing_by_type: dict[str, set[str]],
    ) -> list[SuggestionCandidate]:
        """Suggest papers triaged as shortlisted or cite-later as seed papers.

        Excludes papers already in profile as seed_paper or negative_example.
        """
        # Papers with qualifying triage states
        stmt = (
            select(TriageState.paper_id, TriageState.state)
            .where(TriageState.state.in_(["shortlisted", "cite-later"]))
        )
        result = await session.execute(stmt)
        rows = result.all()

        # Exclusion sets
        existing_seeds = existing_by_type.get("seed_paper", set())
        existing_negatives = existing_by_type.get("negative_example", set())
        excluded = existing_seeds | existing_negatives

        candidates = []
        for paper_id, state in rows:
            if paper_id in excluded:
                continue
            candidates.append(SuggestionCandidate(
                signal_type="seed_paper",
                signal_value=paper_id,
                reason=f"Triaged as {state}",
                score=2.0 if state == "shortlisted" else 1.5,
            ))

        return candidates

    async def _suggest_queries(
        self,
        session: AsyncSession,
        existing_by_type: dict[str, set[str]],
    ) -> list[SuggestionCandidate]:
        """Suggest saved queries with run_count >= threshold."""
        stmt = (
            select(SavedQuery.slug, SavedQuery.run_count)
            .where(SavedQuery.run_count >= QUERY_RUN_THRESHOLD)
        )
        result = await session.execute(stmt)
        rows = result.all()

        existing_queries = existing_by_type.get("saved_query", set())

        candidates = []
        for slug, run_count in rows:
            if slug in existing_queries:
                continue
            candidates.append(SuggestionCandidate(
                signal_type="saved_query",
                signal_value=slug,
                reason=f"Run {run_count} times",
                score=float(run_count),
            ))

        return candidates

    async def _suggest_authors(
        self,
        session: AsyncSession,
        existing_by_type: dict[str, set[str]],
    ) -> list[SuggestionCandidate]:
        """Suggest authors appearing in 3+ shortlisted/cite-later papers.

        Parses authors_text from each qualifying paper, normalizes names,
        counts frequency, and filters to those at or above AUTHOR_THRESHOLD.
        """
        # Get papers with qualifying triage states
        stmt = (
            select(Paper.authors_text)
            .join(TriageState, TriageState.paper_id == Paper.arxiv_id)
            .where(TriageState.state.in_(["shortlisted", "cite-later"]))
        )
        result = await session.execute(stmt)
        rows = result.all()

        # Count author frequencies
        author_counts: Counter[str] = Counter()
        for (authors_text,) in rows:
            if authors_text:
                for author in parse_authors(authors_text):
                    if author:  # skip empty strings
                        author_counts[author] += 1

        existing_authors = existing_by_type.get("followed_author", set())

        candidates = []
        for author, count in author_counts.items():
            if count < AUTHOR_THRESHOLD:
                continue
            if author in existing_authors:
                continue
            candidates.append(SuggestionCandidate(
                signal_type="followed_author",
                signal_value=author,
                reason=f"Appears in {count} shortlisted/cite-later papers",
                score=float(count),
            ))

        return candidates

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    async def _get_profile(
        self, session: AsyncSession, slug: str
    ) -> InterestProfile | None:
        """Load profile with signals by slug."""
        from sqlalchemy.orm import selectinload

        stmt = (
            select(InterestProfile)
            .where(InterestProfile.slug == slug)
            .options(selectinload(InterestProfile.signals))
        )
        result = await session.execute(stmt)
        return result.scalar_one_or_none()

    async def _find_pending_signal(
        self,
        session: AsyncSession,
        profile_id: int,
        signal_type: str,
        signal_value: str,
    ) -> InterestSignal:
        """Find a pending signal matching the given type and value.

        Raises ValueError if no matching pending signal exists.
        """
        stmt = select(InterestSignal).where(
            InterestSignal.profile_id == profile_id,
            InterestSignal.signal_type == signal_type,
            InterestSignal.signal_value == signal_value,
            InterestSignal.status == "pending",
        )
        result = await session.execute(stmt)
        signal = result.scalar_one_or_none()
        if signal is None:
            raise ValueError(
                f"No pending signal ({signal_type}, {signal_value!r}) found"
            )
        return signal
